url: jdbc:teradata://HSTNTDUAT.HEALTHSPRING.INSIDE/DBS_PORT=1025,LOGMECH=LDAP,COLUMN_NAME=on,STRICT_NAMES=OFF
changeLogFile: data_ops_blueprints_tdv_dml/uat.changelog.xml
liquibaseSchemaName: HSETL_WORK
databaseChangeLogTableName: data_ops_blueprints_databasechangelog_uat
databaseChangeLogLockTableName: data_ops_blueprints_tdv_databasechangeloglock_uat
classpath: lib/terajdbc4.jar:lib/liquibase-teradata-4.29.2.jar
parameter.dbEnv=""